# Generated by Django 3.2.6 on 2021-09-17 10:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(validators=[core.models.validate_num]),
        ),
    ]
